Attempting to submit a custom locally built GDS.

diff --git a/.github/workflows/gds.yaml b/.github/workflows/gds.yaml
--- a/.github/workflows/gds.yaml
+++ b/.github/workflows/gds.yaml
@@ -1,47 +1,100 @@
-name: gds
+name: 'Tiny Tapeout Custom GDS Action'
+description: 'This action builds prepares a custom GDS project for submitting to Tiny Tapeout'
+branding:
+  color: purple
+  icon: layers
 
-on:
-  push:
-  workflow_dispatch:
+inputs:
+  tools-repo:
+    description: 'Override tt-support-tools repository'
+    default: 'TinyTapeout/tt-support-tools'
+    required: false
+    type: string
+  tools-ref:
+    description: 'Override tt-support-tools branch/tag/commit'
+    default: 'tt07'
+    required: false
+    type: string
+  top_module:
+    description: 'tt_um_lisa'
+    required: true
+  gds_path:
+    description: 'gds/tt_um_lisa.gds'
+    required: true
+  lef_path:
+    description: 'lef/tt_um_lisa.lef'
+    required: true
+  verilog_path:
+    description: 'pnl/tt_um_lisa.pnl'
+    default: ''
 
-jobs:
-  gds:
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout repo
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
+runs:
+  using: 'composite'
+  steps:
+    - name: Create commit_id.json
+      shell: bash
+      run: |
+        mkdir -p tt_submission
+        jq -n \
+          --arg app "custom_gds action" \
+          --arg repo "${{ github.server_url }}/${{ github.repository }}" \
+          --arg commit "${{ github.sha }}" \
+          --arg workflow_url "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" \
+          '{app: $app, repo: $repo, commit: $commit, workflow_url: $workflow_url}' \
+          > tt_submission/commit_id.json
 
-      - name: Build GDS
-        uses: TinyTapeout/tt-gds-action@tt06-openlane2
-        with:
-          openlane-tag: 2.0.4
-  
-  precheck:
-    needs: gds
-    runs-on: ubuntu-latest
-    steps:
-      - name: Run Tiny Tapeout Precheck
-        uses: TinyTapeout/tt-gds-action/precheck@tt07
+    - name: Copy GDS / LEF files to tt_submission
+      shell: bash
+      run: |
+        cp ${{ inputs.gds_path }} tt_submission/${{ inputs.top_module }}.gds
+        cp ${{ inputs.lef_path }} tt_submission/${{ inputs.top_module }}.lef
+        
+        touch tt_submission/${{ inputs.top_module }}.v
+        if [ -n "${{ inputs.verilog_path }}" ]; then
+          cp ${{ inputs.verilog_path }} tt_submission/${{ inputs.top_module }}.v
+        fi
 
-  gl_test:
-    needs: gds
-    runs-on: ubuntu-latest
-    steps:
-      - name: checkout repo
-        uses: actions/checkout@v4
-        with:
-          submodules: recursive
+    - name: Publish tt_submission artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: tt_submission
+        path: |
+          info.yaml
+          LICENSE
+          docs/*
+          tt_submission/*
 
-      - name: GL test
-        uses: TinyTapeout/tt-gds-action/gl_test@tt07
+    # Install packages for 'Render PNG from GDS' step:
+    - name: Install prerequisites
+      uses: awalsh128/cache-apt-pkgs-action@latest
+      with:
+        packages: librsvg2-bin pngquant # librsvg2-bin for rsvg-convert; pngquant for heavy PNG compression.
+        version: tt07
 
-  viewer:
-    needs: gds
-    runs-on: ubuntu-latest
-    permissions:
-      pages: write      # to deploy to Pages
-      id-token: write   # to verify the deployment originates from an appropriate source
-    steps:
-      - uses: TinyTapeout/tt-gds-action/viewer@tt07
+    - name: Checkout tt-support-tools repo
+      uses: actions/checkout@v4
+      with:
+        repository: "${{ inputs.tools-repo }}"
+        path: tt
+        ref: "${{ inputs.tools-ref }}"
+
+    - name: Setup python
+      uses: actions/setup-python@v5
+      with:
+        python-version: '3.11'
+        cache: 'pip' # caching pip dependencies
+
+    - name: Install tt-support-tools dependencies
+      shell: bash
+      run: pip install -r tt/requirements.txt
+
+    - name: Render PNG from GDS
+      shell: bash
+      run: './tt/tt_tool.py --create-png 2>&1 || echo "WARNING: Failed to render PNG preview from GDS; error $?"'
+      env:
+        GDS_PATH: ${{ inputs.gds_path }}
+
+    - name: Upload gds_render (png) artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: gds_render
